keys:
  - &admin_nerd age1ne8tx80l6lwgds644jpuvp4hfeyayuwh23lae3ull6xfysfp6efqgrc42f
  - &server_bebop age1cec9wu3fpf07xve6vg44h356vwea6n8v7rvw0jp94waw9up5a94sl0atz0
creation_rules:
  - path_regex: secrets/default.yaml$
    key_groups:
      - age:
          - *admin_nerd
          - *server_bebop
  - path_regex: secrets/tailscale/default.yaml$
    key_groups:
      - age:
          - *admin_nerd
          - *server_bebop
  - path_regex: secrets/networking/default.yaml$
    key_groups:
      - age:
          - *admin_nerd
          - *server_bebop
