networking:
    wireless:
        home:
            ssid: ENC[AES256_GCM,data:e5lm2ggKOyef/Rtj8EbEHQ==,iv:4w8oQZr+Zlb/nEO5/k1qB05ZU7duMXxyq2VrL1+OQG8=,tag:yVxWUImWTg5UB/EKQzz3EQ==,type:str]
            password: ENC[AES256_GCM,data:6rBXbXqxt3g=,iv:jT7UBvFbce5YsqxDrgEbJQn7a8p1cInk2JXL1BiVwJ4=,tag:9OVpoCQObpv3ZTjc0tY1vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rvdume3yfwjxu2wc64dmkmc06qsm7fe0fvrpqt8mdrdksqx75vspwns56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ1RlVE1YaG9QWlJYcG81
            QzVYNFIrSzdqS3crTEJVa0t4Q0dHYTJyQ3pVCmR6WjR5Njd1dmtzWmhaaUZaaVJ5
            Z1I1SjA3eUpzVDFaY0ZQL3dFYTlMYWcKLS0tIHdsM2N5aUZna2RUSEhUdC94U1pj
            U2RseXpnWTN6Q3dVSmZiM2dmcGJLRDQKC5ULf84PjPUK+5hrtN57QnQtzFFfPANI
            QeA81cTa8oETho65ZQEX7gOgNAaDiibxf6SZ60pK4Ri0YcFvZx8ydw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10e6ptnwuy76r2rx7cncp5gvh06eghvdungnhrkkea8t32caxjdxshwcy83
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TEFHQjRhOVhqTkdsUHB6
            dklyNGsveHFnTWZyVFUvdVIxR3lqR3RLdFIwClR3Uk5ibDlwTEk4RXphV1pMaktT
            THMyM2ZjdkJnMzB2elhoOFRnQTl3RVkKLS0tIEJKVG8yK012WkdqbXV6SjNoYUht
            S2pUaFN3YVRYb2FVOVdlaVlBakhkVm8KpkTPSXBBkHKW5CY8amKsTeraA4PqyZ2q
            IfVnWL0k/cNjDKAWIy/PxSpNcYf6iSc0qyK48sMThIpEb45s1bQmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T16:37:23Z"
    mac: ENC[AES256_GCM,data:QxoGDCe4uV//3SR18BEv4YRvtCTcBwnPwxiLVkbNXOv+Jl7d08s7fssnf509ldlFbK2QzS6wyxIwTdGdDqPoaOTZx+P9sbnVher5aBhOhfAfwmqRkf9Ct0nd1K+ANDapdLLldqPEnGk10oztktLPGIe/ox/VpYmTDqHP1VVzYIw=,iv:wzuR6SGIDBkPUxBR1zMw1eUbsJJA9BmV6hYM4kkgsh4=,tag:ydiN3Cvuez/yd5lcMWnyQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
