auth-key: ENC[AES256_GCM,data:GKQR/pVv4BNVyE/hGg0IKq+4xk0E5k3y0OdeMA6WKyd2dIEvVVKyNkmG6ZzqDeDlUm0mjQGzu4V35Jpy3Q==,iv:oFm074wo4PrXnV3244iuYTV4xYSseDwLN9jvs3WoFdc=,tag:ATLyiEHwF2msxC6z9XNsPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rvdume3yfwjxu2wc64dmkmc06qsm7fe0fvrpqt8mdrdksqx75vspwns56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NUNvclRxRmZGQ0lqaktp
            cVhPRmxQWkNlZVRlb05pU0wvWGpQaGNEZUFZCjRScXJOTUtjbDA0YmxDNStZNlc2
            a0dTUWFrTzdoQ2RTNXV2UTl2b0NvUlkKLS0tIDlZNXlDbEhGcER4Q3pxZzVTTFVI
            dkJ3czZFK3hWSGJJREFLMzR1VEorTGcKoN1T67GL9FWgWOZ2sxLsdn+FZ01MWWUa
            2KeVFEdV2Xz0RWWshb5lab/c7d+nd8qiyscKdi4+q/28TGqJXVbUfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10e6ptnwuy76r2rx7cncp5gvh06eghvdungnhrkkea8t32caxjdxshwcy83
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYldWTXpVZWpvbmJWRUV0
            RXh2eFlRN0lPUFN2NkJkRHRDOStFMzVpV200Ck9LV1Nla3Vua0M4K1JDMXU1UGNZ
            UGQ2di9VU1p6ZHVuUGpkUzduNnl3R2sKLS0tIDMrdlpnbG1HcVJvakdaaVJVeXdH
            YXAvMnMzZmdWTThtQnVWSkRBQlozTEkK6WhME0Ryyqs+XdZp16mMwB3nN6q/td1+
            5UL+G97x86KAaWtONvcX3GX0hGRcQknPtlPKyVFhC5AZ1s3mRIZIJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T16:34:57Z"
    mac: ENC[AES256_GCM,data:vvoBcdvhNfIYQZ2bjyVeB3X/W/pdjcUZx5exlTKq0n0FoCIFF9AFD4XmY/UcSXWzQoLJIkvrVP/+kSgVDHEwQW17jpykU6MsWGuH0aqPBXC6xDoGFK8D3Bh33SXsBsb7i6+P2apzDS/BmsOlN+DPhRCGb/PseAj99901U8HPSh0=,iv:58nw/xfvhE5mCuKUVpYCjqqrT9bp+7DWk9FD9FfKOsI=,tag:BE+Qr56pYhPnhnX69rNVBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
