initial-password: ENC[AES256_GCM,data:EepfGoT/lhs=,iv:2kzuKHdO4uJXLKWFdggW0Zd3RMCXtaJG0RfcomJnD3A=,tag:X4PvVSR5Pq28vg0jr6zDwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rvdume3yfwjxu2wc64dmkmc06qsm7fe0fvrpqt8mdrdksqx75vspwns56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUlAwVzhBbzlDeFhaTlhZ
            eGdFWFc0TGlpb2l1ZVdnRWNZRGFKNXdlN25nCnhReTY3V002bXZEL2dyUEJpUnRi
            MUpaRnM3bkdvWVpKNWFWWHExYXJNeFUKLS0tICtTalJkTnlhRkpwWUxSMDc1SmpN
            SUNFdjJ0TTBLdjVsSUpHeDZVa25EWmcK2MFFSH94Oqcce/DdhP8X9lAee4TmR3jd
            rcJ4HgT6y3AgETnsTXXIm8rAfNf9aOOLWA5GwXLs7heYJBPC47mViw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10e6ptnwuy76r2rx7cncp5gvh06eghvdungnhrkkea8t32caxjdxshwcy83
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRK2h5bExKZzN6M3ZRUUph
            cUhaTGZ2aURqZ1dmZ3ZCdVpCRkp1VG9KOHdNCjNZaXJOREYvcndYcXRZeFlRRlAy
            Q0NOM005am9vY0FyaTcrRFl0V21UaEkKLS0tIGR5WS9rc2ZVZGptWGFVeWsrTGZK
            SkxJOGpJQ1VxcFNzVzVpTkhsbmJldVUKYOFwhfvYyBQzGVysI+IDPML22HFHmen/
            HIVAMm931tnpqun1KKwX19w+lqzaOlWBZPMmo8Tb0lXA6+di76rGrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T16:39:46Z"
    mac: ENC[AES256_GCM,data:yzgOtlEZOXMJkoK+p0LaiY2hx8Iuy7l2S+QKreB5v3qIJoEu9CkmXGS1Gbt7CuEkRAMFZUL9DV2t4pmS/AHCrzMeRxVQHkgdeDLWSkHDjtJv+hebXIqII5WA7QgH+FiQWvtKwRYOLaZAPwpMPsg5nDXLLtuq2XhQxltCbAbIp3w=,iv:iv8sa8/T/IGz0ZY2Psy9I38Rgktr+LVL9KVgjz7LGSE=,tag:krqWJO46RzebLNHhbrBR5w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
